blog/urls.py
from django.urls import path
from blog.views import *
app_name = 'blog'

urlpatterns = [
    path('', index, name='index'),
    path('post/<pk>/', detail, name='detail'),
    path('archives/<int:year>/<int:month>/', archives, name='archives'),
    path('category/<pk>/', category, name='category'),
    path('tag<pk>/', tag, name='tag'),
    path('search/', search, name='search'),
    path('about', about, name='about'),

]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('', include('comments.urls', namespace='comments'))
]

comments/urls.py
from django.urls import path
from comments.views import *

app_name = 'comments'

urlpatterns = [
    path(r'^comment/post/(?P<post_pk>[0-9]+)/$', post_comment, name='post_comment'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class User(AbstractUser):
    qq = models.CharField(max_length=20, verbose_name="QQ号")
    tel = models.CharField(max_length=15, verbose_name="电话")

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name
        ordering = ("id",)


class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name='分类名')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = verbose_name
        ordering = ("id",)


class Tag(models.Model):
    name = models.CharField(max_length=20, verbose_name='标签名')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name
        ordering = ("id",)


class Post(models.Model):
    title = models.CharField(max_length=50, verbose_name='文章标题')
    content = models.TextField(verbose_name='文章内容')
    created_time = models.DateTimeField(verbose_name='创建时间')
    modified_time = models.DateTimeField(verbose_name='最后一次修改时间')
    excerpt = models.CharField(max_length=200, blank=True, verbose_name='文章摘要')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='文章类型')
    tag = models.ManyToManyField(Tag, blank=True, verbose_name='文章标签')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='文章作者')
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        ordering = ("-created_time", "-id")

comments/models.py
from django.db import models


class Comments(models.Model):
    name = models.CharField(max_length=100, verbose_name='姓名')
    email = models.EmailField(max_length=50, verbose_name='邮箱')
    url = models.URLField(blank=True, verbose_name='个人网站')
    text = models.TextField(verbose_name='评论')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, verbose_name='评论文章')

    def __str__(self):
        return self.text[:20]

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name
        ordering = ("created_time",)

comments/forms.py
from django import forms
from .models import *


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['name', 'email', 'url', 'text']

blog/views.py
import markdown
from django.shortcuts import render, get_object_or_404
from blog.models import *
from comments.forms import *
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator


def index(request):
    posts = Post.objects.all()
    page = request.GET.get('page')
    paginator = Paginator(posts, 5)
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    return render(request, 'index.html', locals())


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.increase_views()
    post.content = markdown.markdown(post.content,
                                     extensions=[
                                         'markdown.extensions.extra',
                                         'markdown.extensions.codehilite',
                                         'markdown.extensions.toc',
                                     ])
    form = CommentForm()
    comment_list = post.comments_set.all()
    # comment_list = Comments.objects.filter(post=post)

    context = {'post': post,
               'form': form,
               'comment_list': comment_list
               }
    return render(request, 'detail.html', locals())


def archives(request, year, month):
    posts = Post.objects.filter(created_time__year=year)  # , created_time__month=month
    page = request.GET.get('page')
    paginator = Paginator(posts, 5)
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    return render(request, 'index.html', context={'post_list': post_list})


def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    posts = Post.objects.filter(category=cate)
    page = request.GET.get('page')
    paginator = Paginator(posts, 5)
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    return render(request, 'index.html', context={'post_list': post_list})


def tag(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    posts = Post.objects.filter(tag=tag)
    page = request.GET.get('page')
    paginator = Paginator(posts, 5)
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    return render(request, 'index.html', context={'post_list': post_list})


def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = "请输入关键词"
        return render(request, 'index.html', {'error_msg': error_msg})

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(content__icontains=q))
    return render(request, 'index.html', locals())


def about(request):
    return render(request, 'about.html')

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post

from .models import *
from .forms import CommentForm


def post_comment(request, post_pk):
    # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来。
    # 这里我们使用了 Django 提供的一个快捷函数 get_object_or_404，
    # 这个函数的作用是当获取的文章（Post）存在时，则获取；否则返回 404 页面给用户。
    post = get_object_or_404(Post, pk=post_pk)

    # HTTP 请求有 get 和 post 两种，一般用户通过表单提交数据都是通过 post 请求，
    # 因此只有当用户的请求为 post 时才需要处理表单数据。
    if request.method == 'POST':
        # 用户提交的数据存在 request.POST 中，这是一个类字典对象。
        # 我们利用这些数据构造了 CommentForm 的实例，这样 Django 的表单就生成了。
        form = CommentForm(request.POST)

        # 当调用 form.is_valid() 方法时，Django 自动帮我们检查表单的数据是否符合格式要求。
        if form.is_valid():
            # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库，
            # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
            comment = form.save(commit=False)

            # 将评论和被评论的文章关联起来。
            comment.post = post

            # 最终将评论数据保存进数据库，调用模型实例的 save 方法
            comment.save()

            # 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
            # 然后重定向到 get_absolute_url 方法返回的 URL。
            return redirect(post)

        else:
            # 检查到数据不合法，重新渲染详情页，并且渲染表单的错误。
            # 因此我们传了三个模板变量给 detail.html，
            # 一个是文章（Post），一个是评论列表，一个是表单 form
            # 注意这里我们用到了 post.comment_set.all() 方法，
            # 这个用法有点类似于 Post.objects.all()
            # 其作用是获取这篇 post 下的的全部评论，
            # 因为 Post 和 Comment 是 ForeignKey 关联的，
            # 因此使用 post.comment_set.all() 反向查询全部评论。
            # 具体请看下面的讲解。
            comment_list = post.comments_set.all()
            # comment_list = Comments.objects.filter(post=post)
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'detail.html', context=context)
    # 不是 post 请求，说明用户没有提交数据，重定向到文章详情页。
    return redirect(post)

blog/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <div>
        <h1 class="page-title">关于我</h1>
        <article class="post">
            <div class="entry-content clearfix">
                <figure class="img-responsive-center">
                    <img class="img-responsive" src="{% static 'img/about.jpg' %}" alt="Developer Image">
                </figure>
                <p>
                    <br>
                    此项目完整代码托管在 <a href="https://github.com/iddlee/blog">GitHub：Blog</a> 中
                </p><hr>
                <p>
                    此项目，是在基于"追梦人物的博客"教程，进行学习时所建项目，后将其进行改进，采用Django2.0，Python3.6
                    进行建设，优化了部分后端代码，同时改进了模板。
                </p><hr>
            </div>
        </article>
    </div>


{% endblock main %}

blog/templates/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <link rel="shortcut icon" type="image/ico" href="{% static 'img/favicon.ico' %}" />
    <title>青年老屋</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>


<script>
function change_pic(){
    var imgObj = document.getElementById("weibo");
    if(imgObj.getAttribute("src") == "{% static 'img/weibo.png' %}")
    {
        imgObj.src="{% static 'img/ewm_wb.png' %}";
    }
    else
    {
        imgObj.src="{% static 'img/weibo.png' %}";
    }
}
</script>


<script>
function change_pic1(){
    var imgObj1 = document.getElementById("weixin");
    if(imgObj1.getAttribute("src") == "{% static 'img/weixin.png' %}")
    {
        imgObj1.src="{% static 'img/wx_ewm.jpg' %}";
    }
    else
    {
        imgObj1.src="{% static 'img/weixin.png' %}";
    }
}
</script>


</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs- 8" >
                <div class="logo" >
                    <a href="/">
                        <h1><img src="{% static 'img/logo.jpg' %}"></h1>
                    </a>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right" style="padding-top: 15px">
                            <li class="cl-effect-11"><a href="/" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="/admin" data-hover="后台管理">后台管理</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box" style="padding-top: 15px">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="con      tent-body">
    <div class="container">
        <div class="row">
            <main class="col-md-9">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-3">

                <div class="rss">
                    <span class="icon ion-android-favorite-outline"></span> 关注我<br><br>
                    <div class="focus">
                        <img src="{% static "img/weibo.png" %}" id="weibo" onmouseover="change_pic()" onmouseout="change_pic()">&nbsp;&nbsp;&nbsp;
                        <img src="{% static "img/weixin.png" %}" id="weixin" onmouseover="change_pic1()" onmouseout="change_pic1()">&nbsp;&nbsp;&nbsp;
                        <a href="https://github.com/iddlee" target="_blank"><img src="{% static 'img/github.png' %}" class="" ></a>
                    </div>
                </div>

                {% block toc %}
                {% endblock toc %}

                <div class="widget widget-recent-posts">
                <hr>
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章！
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        {% empty %}
                            暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.num_posts }})</span></a>
                        </li>
                        {% empty %}
                            暂无分类！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                        暂无标签！
                        {% endfor %}
                    </ul>
                </div>

            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2018 青年老屋<br>
                    logo源自<a href="http://www.techuangyi.com/tzone-16971.html" target="_blank">特创易-HStudio</a>丨技术支持：Python3.6、Django2.0
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="/">首页</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="/admin">后台管理</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'js/script.js' %}"></script>


<div>
    <a href="#" class="backToTop">返回顶部</a>
</div>


</body>
</html>

blog/templates/detail.html
{% extends 'base.html' %}

 {% block main %}
    <article class="{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#"><span class="icon ion-ios-paper-outline"></span>  {{ post.category.name }}丨</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}"><span class="icon ion-ios-clock-outline"></span>  {{ post.created_time }}丨</time></a></span>
                            <span class="post-author"><a href="#"><span class="icon ion-android-person"></span>  {{ post.author }}丨</a></span>
                            <span class="comments-link"><a href="#"><span class="icon ion-chatbox"></span>  {{ post.comments_set.count }}丨</a></span>
                            <span class="views-count"><a href="#"><span class="icon ion-eye"></span>  {{ post.views }}</a></span>
                        </div>
                    </header>
                    <div>
                        {% for tag in post.tags.all %}
                            {{ tag.name }}
                        {% endfor %}
                    </div>
                    <div class="entry-content clearfix">
                        {{ post.content|safe }}
                        <div class="widget widget-tag-cloud">
                            <ul>
                            标签：
                                {% for tag in post.tag.all %}
                                    <li><a href="{% url 'blog:tag' tag.pk %}"># {{ tag.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                 {{ form.name }}
                                 {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ form.text.id_for_label }}">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ post.comments_set.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date">{{ comment.created_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            暂无评论
                            {% endfor %}
                        </ul>
                    </div>
                </section>
 {% endblock main %}

{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <ul>
            <li>
                <a href="#">教程特点</a>
            </li>
            <li>
                <a href="#">谁适合这个教程</a>
            </li>
            <li>
                <a href="#">在线预览</a>
            </li>
            <li>
                <a href="#">资源列表</a>
            </li>
            <li>
                <a href="#">获取帮助</a>
            </li>
        </ul>
    </div>
{% endblock toc %}

blog/templates/index.html
{% extends 'base.html' %}

{% block main %}
    {% if error_msg %}
    <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#"><span class="icon ion-ios-paper-outline"></span>  {{ post.category.name }}丨</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                                          datetime="{{ post.created_time }}"><span class="icon ion-ios-clock-outline"></span>  {{ post.created_time }}丨</time></a></span>
                    <span class="post-author"><a href="#"><span class="icon ion-android-person"></span>  {{ post.author }}丨</a></span>
                    <span class="comments-link"><a href="#"><span class="icon ion-chatbox"></span>  {{ post.comments_set.count }}丨</a></span>
                    <span class="views-count"><a href="{{ post.get_absolute_url }}"><span class="icon ion-eye"></span>  {{ post.views }}</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">|👆详细阅读👆 |<span class="meta-nav"></span></a><hr>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}

    {#分页#}
{#    <div class="pagination col-md-2">#}
{#        <span class="step-links">#}
{#            {% if posts.has_previous %}#}
{#                <a href="?page=1">&laquo; 首页</a>#}
{#                <a href="?page={{ posts.previous_page_number }}">上一页</a>#}
{#            {% endif %}#}
{##}
{#            <span class="current">#}
{#                Page {{ posts.number }} of {{ posts.paginator.num_pages }}#}
{#            </span>#}
{##}
{#            {% if posts.has_next %}#}
{#                <a href="?page={{ posts.next_page_number }}">下一页</a>#}
{#                <a href="?page={{ posts.paginator.num_pages }}">末页 &raquo;</a>#}
{#            {% endif %}#}
{#        </span>#}
{#    </div>#}

    <nav aria-label="...">
        <ul class="pager">
            {% if post_list.has_previous %}
                <li><a href="?page={{ post_list.previous_page_number }}">上一页丨</a></li>
            {% endif %}
            {% if post_list.has_previous or post_list.has_next %}
            <li><a href="?page={{ post_list.number }}">第 {{ post_list.number }} 页</a></li>
            {% endif %}
            {% if post_list.has_next %}
                <li><a href="?page={{ post_list.next_page_number }}">丨下一页</a></li>
            {% endif %}
        </ul>
    </nav>


{% endblock main %}